### ISSUE TITLE
Set and Collector boosters / booster fun

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-sealed-data#32]
Would there be any problems with adding "boosters" to the PLIST set, and using those to store which cards are available in any given set booster? We could even store information about relative rarities for universes within cards or rare/common list cards.

Example:
```
{
  "data": {
    "booster": {
      "ZNR": {
        "boosters": [{"contents": {"znr_list_common": 1}, "weight":3}, {"contents": {"znr_list_rare": 1}, "weight":1], "boostersTotalWeight": 4, "sheets":{
          "znr_list_common": {"cards": {"plist:161": 1, ...}},
          "znr_list_rare": {"cards": {"plist:241": 1, ...}}
        }
      }
    }
  }
}
```

Information from https://mtg.fandom.com/wiki/The_List/ZNR-SNC and https://www.lethe.xyz/mtg/collation/znr.html

**Comment by taw** [comment]
From what I understand, PLIST content is not in draft boosters, so it wouldn't go into any existing ones.

The main reason none of this is done is amount of effort required, as well as fairly limited information we have.

I can continue doing draft boosters (and Arena boosters since they're pretty much), and after a few tries I gave up on "booster fun" showcase art.

I'm definitely not going to do set boosters, collector boosters etc. unless someone steps in, and is willing to do the work.

If you're interested, right now the system is just code. Right now it's mostly these two files:

* https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/card_sheet_factory.rb
* https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/pack_factory.rb

And also some others like:

* https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_showcase.rb
* https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_has_boosters.rb
* https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_exclude_from_boosters.rb
* https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_base_size.rb

If people are committed to putting in some work, I guess I could setup some separate project with all booster data, [the way I did it for precons](https://github.com/taw/magic-preconstructed-decks).

Data in this repo is completely machine-generated, so it would need to be fixed upstream.

**Comment by axxroytovu** [comment]
I'm already doing the work for collector/set boosters for a different project so I'll see if it's an easy transfer.

**Comment by taw** [comment]
Assuming you probably don't want to edit a lot of code files, one way this kind of collaboration would be a repo with structure like this `data/m10/draft.yml`:

And inside something like:

```
---
packs:
- rate: 9
  contents:
    foil: 1
    commmon: 9
    uncommon: 3
    rare_mythic: 1
- rate: 31
  contents:
    commmon: 10
    uncommon: 3
    rare_mythic: 1
sheets:
  common:
    query: e:m10 r:common size<=base
    size: 121
  uncommon:
    query: e:m10 r:uncommon size<=base
    size: 60
  rare_mythic:
    - query: e:m10 r:rare size<=base
      size: 53
      rate: 2
    - query: e:m10 r:mythic size<=base
      size: 15
      rate: 1
``` 

Then some indexer script would resolve all queries and turn them into machine readable jsons like the ones in this repo.

Unfortunately designing expressive enough system is not straightforward. Even regular foils have convoluted rules, and doing something like BBD this way, ugh.

**Comment by axxroytovu** [comment]
I'll see what I can do. I'll try with ONE first to get the process down, and then work from there. 

Should I close this issue here and reopen it in the magic-search-engine repo?

**Comment by taw** [comment]
It's fine to keep the issue here now.

We'll probably need to iterate the experiment a few times before we figure out something that works.

**Comment by axxroytovu** [comment]
Here's my first go at a file for the ONE set boosters.
[ONE_SET.txt](https://github.com/taw/magic-sealed-data/files/11022204/ONE_SET.txt)

The things that need development:

I need to come up with a way to effectively search for "the normal printing of a card that has a showcase treatment" and "the normal printing of a card that does not have a showcase treatment". I handled this in my other code by downloading all of the treatments of a card into one object, and treating it differently depending on how many versions it had. In the file above I just included "has:showcase" and "-has:showcase" in the query.

Getting specific cards from the List. I can manually grab the spreadsheet from https://mtg.fandom.com/wiki/The_List/ and save it as a .csv file, but that might be more manual than you were hoping.

**Comment by axxroytovu** [comment]
There are also two ways to handle the wildcard slots. I built them as one big sheet, but that's not really how they work. It would be more accurate to use three separate sheets for the common/uncommon/rare_mythic wildcards, and have lots of possible pack configurations to match. Let me know what you think the best solution there is.

**Comment by taw** [comment]
This looks really complicated, and it's only half done.

If we go forward with it, I'd probably need to code a bunch of simple sheets first before we even get to this kind of complexity.

A few techniques I'm already using:

* to combine multiple queries into one sheet, sometimes it makes more sense to think in terms of card sheet multiples (like every R is 2x, every M is 1x, on a RM sheet), and sometimes in terms of sheet probabilities (like 1/8 chance of RM in foil slot). This could simplify some of the crazy high multiplies (in principle one system can be converted to the other by simple formula, but numbers can get really high this way).
* these can be combined recursively, like with foil example, where one of the options is actually R+M. The code then flattens it, but it makes more sense for humans.
* I already implemented explicit print sheet support, like https://github.com/taw/magic-search-engine/blob/master/data/print_sheets/Alliances_checklist.txt or https://github.com/taw/magic-search-engine/blob/master/data/print_sheets/abur/2ed-c.txt or https://github.com/taw/magic-search-engine/blob/master/data/print_sheets/mb1/red_a.txt Unfortunately the way it works now wouldn't work for PLIST, as it assumes a printing just has some specific sheet name + rate, like https://mtg.wtf/card/arn/9/Repentant-Blacksmith is "rare (U2)", so the system would need to be expanded, so it can be "common (SNC1 ONE1)" or such.

Some actionable things:

- [x] whatever happens, I should probably implement `is:showcase`. It needs manually specifying showcase card number ranges for each set.
- [x] and then `has:showcase`, as it can be automatically calculated from `is:showcase` (a card matches `has:showcase` if there's a card with same name in the same set that matches `is:showcase`)
- [x] Even if it's not actually going anywhere yet, maybe we should create machine readable files like `data/print_sheets/plist/one.txt` with list of all PLIST cards in ONE (and if more complicated, sheets and multiplies like C1 U2 etc.). Do you want to do this?
- [x] There's already `in:booster` queries, but maybe I could add queries like `booster:one` or `booster:one-set`. This would mostly be useful for cards in one set that appear in another set's boosters, and not directly helpful for this.

It sort of looks like a followup for `booster:one` could be something like `sheet:plist/one-c` but this doesn't quite work as queries don't have concept of multiples.

Do you want to give this 4 step plan a go (3 for me, and 1 for you), and then we can get back to think about next steps?

**Comment by axxroytovu** [comment]
Most of the complexity is identifying which cards are and are not showcase, so having `is:showcase` and `has:showcase` would be a huge boost. Maybe I could add tagged ranges to the top of the file? That would let us reuse the same functions for showcase, borderless, extended-art, etched, etc. Let me know if you want any help implementing this.

If it's any use, both Scryfall and MTG.WTF accept frame:showcase as valid search parameters.

I can start building a plist machine readable file. That shouldn't be too difficult from what I already have so I can get that built pretty quickly. 

I don't know that `booster:one` is super useful. Most of the other set cards are from the commander set and jumpstart rares, which don't show up in draft boosters. But the showcase mythic praetors that show up in draft boosters are a one-time thing, which we probably don't need to develop a special function for.

**Comment by taw** [comment]
Actually we already have [`is:showcase`](https://mtg.wtf/card?q=is%3Ashowcase+e%3Aone) based on mtgjson data, so there's no extra work here.

**Comment by taw** [comment]
[`has:showcase`](https://mtg.wtf/card?q=e%3Aone+has%3Ashowcase+-%2B%2B) added

**Comment by axxroytovu** [comment]
csv for The List: [PLIST_SLX_DISTR.csv](https://github.com/taw/magic-sealed-data/files/11023900/PLIST_SLX_DISTR.csv)

**Comment by axxroytovu** [comment]
Now that you have is:showcase and has:showcase, you can test it on the normal draft boosters to see if it works. Here's the code for the ONE common and uncommon sheets: 

```
  common:
    - query: e:one r:common is:showcase
      size: 6
      rate: 1
    - query: e:one r:common size<=base has:showcase
      size: 6
      rate: 2
    - query: e:one r:common size<=base -has:showcase
      size: 95
      rate: 3
  uncommon:
    - query: e:one r:uncommon is:showcase
      size: 7
      rate: 1
    - query: e:one r:uncommon size<=base has:showcase
      size: 7
      rate: 2
    - query: e:one r:uncommon size<=base -has:showcase
      size: 53
      rate: 3
```

**Comment by axxroytovu** [comment]
I was able to get the queries working if I added `-is:foilonly` to the showcase searches. Because the step and compleat foils and oil slick foils are a different card number it was screwing with the uncommon searches. Removing the "foil only" versions cleans up most of the problems.

```
  common:
    - query: e:one r:common is:showcase -is:foilonly ++
      size: 6
      rate: 1
    - query: e:one r:common size<=base has:showcase
      size: 6
      rate: 2
    - query: e:one r:common size<=base -has:showcase
      size: 95
      rate: 3
  uncommon:
    - query: e:one r:uncommon is:showcase -is:foilonly ++
      size: 7
      rate: 1
    - query: e:one r:uncommon size<=base has:showcase
      size: 7
      rate: 2
    - query: e:one r:uncommon size<=base -has:showcase
      size: 53
      rate: 3
```
