### ISSUE TITLE
MOM

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#34]
Hi,
Apparently MOM boosters are a bit more convoluted than the latest sets.
One Reddit user breaks it down here:
https://www.reddit.com/r/lrcast/comments/12lf1xh/understanding_the_contents_of_a_mom_booster/
Usual Wizards source:
https://magic.wizards.com/en/news/feature/collecting-march-of-the-machine

**Comment by taw** [comment]
Over the last weeks I switched the booster system from fairly complicated code to YAML files which should be usable for the public. [Here's the folder with all data](https://github.com/taw/magic-search-engine/tree/master/data/boosters).

Right now there's not much documentation, and it's been just me and @axxroytovu writing them, but it would be great if other people contributed as well. I recommend skipping boosterfun content at first, and just doing basic one.

Most basic version of the yaml for a new set would be `MOM.yaml` with this content:

```yaml
pack:
- basic: 1
  common: 10
  uncommon: 3
  rare_mythic: 1
  chance: 2
- basic: 1
  common: 9
  uncommon: 3
  rare_mythic: 1
  foil: 1
  chance: 1
```

With all the standard sheet types defined in `common.yaml`.
