### ISSUE TITLE
A couple of missing "balance"

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#36]
Hi,
I believe the following sheets are missing the "balance: true" descriptor:
* LCI: sfcCommonWithShowcase
* LTR: commonWithShowcase
* VOW: sfcCommonWithShowcase

Also, I think currently the sfcCommonWithShowcase for LCI contains caves which are marked with the "L" rarity.

**Comment by axxroytovu** [comment]
Hmm. I think this is a bigger issue than I thought. All three of these reference the common `sfc_common_with_showcase` sheet, which is correctly identified as balance: true. Something under the hood is removing that flag, and modifying the sheet doesn't have any effect.

**Comment by taw** [comment]
I checked the issue. For VOW it's all in YAMLs.

`vow.yaml` defines its own `sfc_common_with_showcase`, without `balanced` flag:

```
sheets:
  sfc_common_with_showcase:
    # Showcase treatments 1/3 for relevant cards
    any:
    - rawquery: "e:{set} r:c promo:boosterfun -is:foilonly -frame:extendedart is:sfc is:paper -promo:draculaseries"
      rate: 1
    - query: "r:c alt:(e:{set} r:c promo:boosterfun -is:foilonly -frame:extendedart -promo:draculaseries) is:sfc"
      rate: 2
    - query: "r:c -alt:(e:{set} r:c promo:boosterfun -is:foilonly -frame:extendedart -promo:draculaseries) is:sfc"
      rate: 3
```

Since it's defined here, definition from `common.yaml` (which has balanced flag) isn't used.

I added it to VOW.

**Comment by taw** [comment]
LTR just didn't define balanced flag:

```yaml
  with_showcase:
    any:
    - query: "promo:boosterfun alt:(number:302-331 or number:340-345) alt:number:399-451 -number:299-300 -number>451"
      rate: 1
    - query: "(number:302-331 or number:340-345) -alt:number:399-451"
      rate: 2
    - query: "-alt:(number:302-331 or number:340-345) number:399-451"
      rate: 2
    - query: "is:baseset alt:(e:{set} promo:boosterfun -is:foilonly -frame:extendedart)"
      rate: 4
    - query: "is:baseset -alt:(e:{set} promo:boosterfun -is:foilonly -frame:extendedart)"
      rate: 6
  common_with_showcase:
    filter: "e:{set} r:c"
    use: with_showcase
```

So I added it.
